services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - db
    links:
      - db
    command: npm run start

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
