name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
      - run: yarn install --frozen-lockfile
      - run: yarn test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JensAstrup/shortcut-assistant
